### ISSUE TITLE
Minify static files from koa-static?

### ISSUE THREAD

**Issue by paridigm** [koajs/html-minifier#28]
I'm hoping to minify static files that come from koa-static, however koa-html-minifier doesn't seem to be minifying. 🤔

This is what I've got,

```js
const serve = require('koa-static');

...

// compression
app.use(require('koa-compress')());

// minifier
app.use(require('koa-html-minifier')({
  collapseWhitespace: true
}));

// static server
app.use(serve('public'));
```

And, the resulting code that I see in the browser is still not minified.

NOTE: I also have a REST API with koa-router, but I don't think that should make a difference.

Thanks!

**Comment by tomknappramos** [comment]
I figured that koa-static is setting ctx.body to the content of the static file, so then ctx.body would return to koa-html-minifier with the html that should be minified.
